// Dev-time converter: assets/music/*.mid -> js/audio/tracks.js (note data played by the Web Audio synth).
// Usage: node tools/midi2js.mjs   (re-run after changing a .mid file, then bump CACHE in sw.js)
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const root = fileURLToPath(new URL("..", import.meta.url));
const srcDir = join(root, "assets/music");
const BUCKETS = ["dawn", "day", "dusk", "night"]; // files are ordered 01..04

function parse(buf) {
  let p = 0;
  const u32 = () => { const v = buf.readUInt32BE(p); p += 4; return v; };
  const u16 = () => { const v = buf.readUInt16BE(p); p += 2; return v; };
  const vlq = () => { let v = 0, c; do { c = buf[p++]; v = (v << 7) | (c & 127); } while (c & 128); return v; };
  if (buf.toString("latin1", 0, 4) !== "MThd") throw new Error("not a MIDI file");
  p = 8;
  u16(); const ntracks = u16(), division = u16();
  const tempos = [], notes = [], programs = {};
  let name = "", timeSig = 4;
  for (let t = 0; t < ntracks; t++) {
    p += 4;
    const end = p + 4 + buf.readUInt32BE(p); p += 4;
    let tick = 0, running = 0;
    const open = new Map();
    while (p < end) {
      tick += vlq();
      let status = buf[p];
      if (status < 0x80) status = running; else p++;
      if (status === 0xff) {
        const type = buf[p++], len = vlq(), data = buf.subarray(p, p + len); p += len;
        if (type === 0x03 && !name) name = data.toString("latin1");
        if (type === 0x51) tempos.push({ tick, usPerBeat: data.readUIntBE(0, 3) });
        if (type === 0x58) timeSig = data[0];
      } else if (status === 0xf0 || status === 0xf7) {
        p += vlq();
      } else {
        running = status;
        const kind = status >> 4, ch = status & 15;
        if (kind === 0xc) { programs[ch] = buf[p]; p += 1; continue; }
        if (kind === 0xd) { p += 1; continue; }
        const a = buf[p], b = buf[p + 1]; p += 2;
        const key = ch * 128 + a;
        if (kind === 0x9 && b > 0) open.set(key, { tick, vel: b });
        else if (kind === 0x8 || (kind === 0x9 && b === 0)) {
          const on = open.get(key);
          if (on) { notes.push({ ch, note: a, start: on.tick, end: tick, vel: on.vel }); open.delete(key); }
        }
      }
    }
  }
  tempos.sort((a, b) => a.tick - b.tick);
  if (!tempos.length || tempos[0].tick > 0) tempos.unshift({ tick: 0, usPerBeat: 500000 });
  const toSec = tick => {
    let sec = 0, last = tempos[0];
    for (const tp of tempos.slice(1)) {
      if (tp.tick >= tick) break;
      sec += ((tp.tick - last.tick) / division) * last.usPerBeat / 1e6;
      last = tp;
    }
    return sec + ((tick - last.tick) / division) * last.usPerBeat / 1e6;
  };
  const bpm = 60e6 / tempos[0].usPerBeat;
  const bar = (60 / bpm) * timeSig;
  const lastEnd = Math.max(...notes.map(n => toSec(n.end)));
  const length = Math.ceil(lastEnd / bar - 0.01) * bar; // loop on a whole bar
  const parts = {};
  for (const n of notes) {
    const id = n.ch;
    parts[id] ??= { program: n.ch === 9 ? -1 : programs[n.ch] ?? 0, drums: n.ch === 9, notes: [] };
    const t = toSec(n.start);
    parts[id].notes.push(+t.toFixed(3), n.note, +Math.max(0.03, toSec(n.end) - t).toFixed(3), n.vel);
  }
  return { name, bpm: Math.round(bpm), length: +length.toFixed(3), parts: Object.values(parts) };
}

const files = readdirSync(srcDir).filter(f => f.endsWith(".mid")).sort();
const tracks = {};
files.forEach((f, i) => { tracks[BUCKETS[i]] = parse(readFileSync(join(srcDir, f))); });
const body = Object.entries(tracks).map(([bucket, tr]) =>
  `  ${bucket}: {\n    name: ${JSON.stringify(tr.name)}, bpm: ${tr.bpm}, length: ${tr.length},\n    parts: [\n${tr.parts.map(pt =>
    `      { program: ${pt.program}, drums: ${pt.drums}, notes: [${pt.notes.join(",")}] },`).join("\n")}\n    ],\n  },`).join("\n");
writeFileSync(join(root, "js/audio/tracks.js"),
  `// Generated by tools/midi2js.mjs from assets/music/*.mid — do not edit by hand.\n` +
  `// Per time bucket: tempo, loop length (s) and parts; notes are flat [timeSec, midiNote, durSec, velocity, ...].\n` +
  `export const TRACKS = {\n${body}\n};\n`);
console.log(files.map((f, i) => `${BUCKETS[i]} <- ${f} (${tracks[BUCKETS[i]].length}s, ${tracks[BUCKETS[i]].parts.length} parts)`).join("\n"));
